// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.

package routers

import (
	"gen_gin_tpl/internal/bootstrap"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type routeGroup struct {
	noAuthView *gin.RouterGroup
	public *gin.RouterGroup
}

func (r *routeGroup) register(db *gorm.DB) {
	// 初始化仓库和服务
	ctx := bootstrap.NewAppContext(db)

	r.noAuthView.GET("/", ctx.WebViewsHandler.ViewsIndexHandler)
	r.noAuthView.GET("/login.html", ctx.WebViewsHandler.ViewsLoginHandler)
	r.noAuthView.GET("/regedit.html", ctx.WebViewsHandler.ViewsRegeditHandler)

	r.public.POST("/public/key", ctx.ApiPublicHandler.PostPublicKey)
	r.public.POST("/public/enums", ctx.ApiPublicHandler.PostHttpCode)
	r.public.GET("/public/ping", ctx.ApiPublicHandler.GetPing)
	r.public.GET("/public/time", ctx.ApiPublicHandler.GetSecond)
	r.public.POST("/public/captcha", ctx.ApiPublicHandler.PostCaptcha)
	r.public.POST("/public/email/code", ctx.ApiPublicHandler.PostSendEmailCaptcha)
}