// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.

package database

import (
	"gen_gin_tpl/internal/bootstrap/database/initdata"
	"gen_gin_tpl/internal/models/auth"
	"gen_gin_tpl/internal/models"
	"gen_gin_tpl/internal/infrastructure/query"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
	"reflect"
)

func AutoMigrate(db *gorm.DB, dbq *query.Query, router gin.RoutesInfo) error {
	err := db.AutoMigrate(
		&auth.Permission{},
		&auth.Role{},
		&auth.RoleGroup{},
		&auth.RolePermission{},
		&auth.UserRole{},
		&models.Config{},
		&models.CorsWhitelist{},
		&models.Enums{},
		&models.Token{},
		&models.User{},
	)

	if err != nil {
		return err
	}
	
	v := reflect.ValueOf(&initdata.InitData{Router: router, Q: query.Q})
	for i := 0; i < v.NumMethod(); i++ {
		v.Method(i).Call(nil)
	}
	return nil
}