// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.

package routers

import (
	"gen_gin_tpl/internal/bootstrap"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

type routeGroup struct {
	noAuth *gin.RouterGroup
	noAuthView *gin.RouterGroup
	public *gin.RouterGroup
}

func (r *routeGroup) register(db *gorm.DB) {
	// 初始化仓库和服务
	ctx := bootstrap.NewAppContext(db)

	r.noAuth.GET("/login", ctx.ApiLoginHandler.GetLogin)

	r.noAuthView.GET("/", ctx.WebViewIndexHandler.GetIndexView)
	r.noAuthView.GET("/login.html", ctx.WebViewLoginHandler.GetLoginView)
	r.noAuthView.POST("/login.html", ctx.WebViewLoginHandler.PostLoginView)
	r.noAuthView.GET("/regedit.html", ctx.WebViewLoginHandler.GetRegeditView)
	r.noAuthView.POST("/regedit.html", ctx.WebViewLoginHandler.PostRegeditView)

	r.public.POST("/public/config", ctx.ApiConfigHandler.PostConfig)
	r.public.POST("/public/key", ctx.ApiPublicHandler.PostPublicKey)
	r.public.POST("/public/enums", ctx.ApiPublicHandler.PostHttpCode)
	r.public.GET("/public/ping", ctx.ApiPublicHandler.GetPing)
	r.public.GET("/public/time", ctx.ApiPublicHandler.GetSecond)
	r.public.POST("/public/captcha", ctx.ApiPublicHandler.PostCaptcha)
	r.public.POST("/public/email/code", ctx.ApiPublicHandler.PostSendEmailCaptcha)
}