export interface FormDataVO {
  OtherIsEmail: boolean,
  OtherDbType: string,
  OtherCacheType: string,
  OtherDataPath: string,
  SQLiteDbName: string,
  MySQLHost: string,
  MySQLPort: number,
  MySQLUsername: string,
  MySQLPassword: string,
  MySQLDbName: string,
  WebHost: string,
  WebPor: number,
  RedisHost: string,
  RedisPort: number,
  RedisPassword: string,
  EmailSMTPHost: string,
  EmailPort: number,
  EmailUsername: string,
  EmailPassword: string,
  LoggerLevel: string,
  LoggerLogPath: string,
  LoggerFormatJson: boolean,
  LoggerCompress: boolean,
  LoggerMaxSize: number,
  LoggerMaxAge: number,
  LoggerMaxBackups: number
}
